version: "3"

services:
##------------------------------------------------------
### OpenTelemetry Collector
##------------------------------------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.21.0
    command: [
      "--config=/conf/collector-config.yaml", 
      "--log-level=DEBUG"
    ]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "55681:55681"
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  # Tracing
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Tracing 
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.22.0
    ports: 
      - "16686:16686"
      - "14268"
      - "14250"

##------------------------------------------------------
### Application Services
##------------------------------------------------------
  ach-processor:
    container_name: ach-processor
    build:
      context: ./services/ach-processor
      dockerfile: Dockerfile
    ports:
      - "3050:3050"

  employee-service:
    container_name: employee-service
    build:
      context: ./services/employee
      dockerfile: Dockerfile
    environment:
        - DATABASE_URL=postgresql://postgres:password@employee-db:5432/employee
    depends_on:
      - employee-db

##------------------------------------------------------
### Databases
##------------------------------------------------------
  employee-db:
    container_name: employee-database
    build:
      context: ./databases/employee
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employee
      