version: "3"

services:
  ach-processor:
    container_name: ach-processor
    build:
      context: ./services/ach-processor
      dockerfile: Dockerfile
    ports:
      - "3050:3050"

  employee-service:
    container_name: employee-service
    build:
      context: ./services/employee
      dockerfile: Dockerfile


  
